# Generated by Django 4.2.16 on 2025-02-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='score',
        ),
    ]
