# Generated by Django 4.2.16 on 2025-02-21 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_lesson_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('objective', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('github_repo', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=255)),
                ('file_paths', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.lesson')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
