# Generated by Django 4.2.16 on 2025-02-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='score',
        ),
    ]
