# Generated by Django 4.2.16 on 2025-02-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file_paths',
        ),
        migrations.RemoveField(
            model_name='task',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='objective',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_hex',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
