# Generated by Django 4.2.17 on 2025-05-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
